### ISSUE TITLE
Add "/" as a delimiter

### ISSUE THREAD

**Issue by dumitrescustefan** [adobe/stringlifier#13]
I would like to use stringlifier to parse HTML console and network logs, for this I'd need to add ``/`` as a separator. 
Now, when running on strings, sometimes the ``/`` gets swallowed up in an UUID or RANDOM. 

If possible, maybe a rule-based cleaning before applying ML would be beneficial, like having a standard 32 UUID (4 fixed groups separated by ``-``) 🤔

**Comment by tiberiu44** [comment]
This should now be handled by the new version.
