### ISSUE TITLE
Is there any paper or article describe the algorithms used here?

### ISSUE THREAD

**Issue by devalex88** [adobe/stringlifier#15]
Hi Adobe team,

Thank you so much for publishing this library. I would like to learn more about the underlying algorithms, so could you please help give me some direction?

Thank you again,
Alex

**Comment by tiberiu44** [comment]
Hi @devalex88 

Thank you for your interest in stringlifier. We didn't publish any white paper of the system. However, I can describe the model briefly.

- it is a sequence labeling ML model that works at character level
- it uses lower-cased character embeddings (100 dimensional vectors) concatenated with case embeddings (4 dimensional vectors) + special symbol for padding (only zeros). The case embeddings cover: lower-case, upper-case and not applicable (for special characters and numbers)
- the architecture is: 2 layers of bidirectional LSTMs (100 dimensions in each direction) -> one hidden layer (500 dimensions) -> output projection softmax (size=number of classes + padding)
- classes are: padding, character, random string, numeric, ip address, UUID, JWT - 7 classes in total

Training: dataset is dynamically generated every time (train+eval)

Runtime: 
- we decode maximum spanning strings composed of characters labeled with the same label type
- we reject random tokens with less than 5 characters

Hope this helps.

Best,
Tiberiu

**Comment by devalex88** [comment]
Hi @tiberiu44,

Thank you so much for the helpful answer.

Have a nice day!
Alex
