### ISSUE TITLE
Add type hints

### ISSUE THREAD

**Issue by ninoseki** [adobe/stringlifier#2]
**Is your feature request related to a problem? Please describe.**

Adding type hints improves DX especially if you are using an IDE like VS code.

**Describe the solution you'd like**

Add type annotations. 

**Describe alternatives you've considered**

N/A.

**Additional context**

I will work on this if this suggestion makes sense.

**Comment by tiberiu44** [comment]
Hi @ninoseki ,

This would indeed be a really nice contribution. If you can work on this, it would be great!

Best,
Tibi
