### ISSUE TITLE
IP Address - Detection

### ISSUE THREAD

**Issue by vimalathithanr** [adobe/stringlifier#9]
**The version number in the package name is getting considered as IP address**
This causes a lot of false positives with the data set we are trying to use. 

**To Reproduce**
1. In the log, please add a log with version number 
2. Example - MongoDB v4.4.2 
3. Run Stringlifier
4. In the output, it shows MongoDB v< IP_ADDR>

**Comment by tiberiu44** [comment]
This bugfix will take a little bit longer. We generate the training data on the fly and we must retrain everything after we include new types of examples. I will keep you updated.

**Comment by vimalathithanr** [comment]
Sure, that helps.

**Comment by vimalathithanr** [comment]
Closing this issue as this one is fixed.
